//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Geral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Geral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intranet.Resources.Geral", typeof(Geral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso Negado.
        /// </summary>
        public static string AcessoNegado {
            get {
                return ResourceManager.GetString("AcessoNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ângulo (º).
        /// </summary>
        public static string AnguloSecoes {
            get {
                return ResourceManager.GetString("AnguloSecoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação do Sistema.
        /// </summary>
        public static string AutenticacaoSistema {
            get {
                return ResourceManager.GetString("AutenticacaoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string Copiar {
            get {
                return ResourceManager.GetString("Copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso..
        /// </summary>
        public static string RegistroAtualizadoSucesso {
            get {
                return ResourceManager.GetString("RegistroAtualizadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inserido com sucesso..
        /// </summary>
        public static string RegistroInseridoSucesso {
            get {
                return ResourceManager.GetString("RegistroInseridoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendimento da motorização.
        /// </summary>
        public static string RendimentoDaMotorizacao {
            get {
                return ResourceManager.GetString("RendimentoDaMotorizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotação.
        /// </summary>
        public static string Rotacao {
            get {
                return ResourceManager.GetString("Rotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambor.
        /// </summary>
        public static string Tambores {
            get {
                return ResourceManager.GetString("Tambores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário expirado..
        /// </summary>
        public static string UsuarioExpirado {
            get {
                return ResourceManager.GetString("UsuarioExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Inativo..
        /// </summary>
        public static string UsuarioInativo {
            get {
                return ResourceManager.GetString("UsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem perfil..
        /// </summary>
        public static string UsuarioSemPerfil {
            get {
                return ResourceManager.GetString("UsuarioSemPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorretos..
        /// </summary>
        public static string UsuarioSenhaIncorreto {
            get {
                return ResourceManager.GetString("UsuarioSenhaIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique as críticas em vermelho..
        /// </summary>
        public static string VerifiqueCritica {
            get {
                return ResourceManager.GetString("VerifiqueCritica", resourceCulture);
            }
        }
    }
}
