//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IntranetModel", "FK_Menu_Menu", "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Intranet.Data.Menu), "Menu1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Intranet.Data.Menu), true)]

#endregion

namespace Intranet.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IntranetEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IntranetEntities object using the connection string found in the 'IntranetEntities' section of the application configuration file.
        /// </summary>
        public IntranetEntities() : base("name=IntranetEntities", "IntranetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IntranetEntities object.
        /// </summary>
        public IntranetEntities(string connectionString) : base(connectionString, "IntranetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IntranetEntities object.
        /// </summary>
        public IntranetEntities(EntityConnection connection) : base(connection, "IntranetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BinaryItens> BinaryItens
        {
            get
            {
                if ((_BinaryItens == null))
                {
                    _BinaryItens = base.CreateObjectSet<BinaryItens>("BinaryItens");
                }
                return _BinaryItens;
            }
        }
        private ObjectSet<BinaryItens> _BinaryItens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HistoryLogin> HistoryLogin
        {
            get
            {
                if ((_HistoryLogin == null))
                {
                    _HistoryLogin = base.CreateObjectSet<HistoryLogin>("HistoryLogin");
                }
                return _HistoryLogin;
            }
        }
        private ObjectSet<HistoryLogin> _HistoryLogin;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HistoryModules> HistoryModules
        {
            get
            {
                if ((_HistoryModules == null))
                {
                    _HistoryModules = base.CreateObjectSet<HistoryModules>("HistoryModules");
                }
                return _HistoryModules;
            }
        }
        private ObjectSet<HistoryModules> _HistoryModules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemMessage> SystemMessage
        {
            get
            {
                if ((_SystemMessage == null))
                {
                    _SystemMessage = base.CreateObjectSet<SystemMessage>("SystemMessage");
                }
                return _SystemMessage;
            }
        }
        private ObjectSet<SystemMessage> _SystemMessage;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BinaryItens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBinaryItens(BinaryItens binaryItens)
        {
            base.AddObject("BinaryItens", binaryItens);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HistoryLogin EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHistoryLogin(HistoryLogin historyLogin)
        {
            base.AddObject("HistoryLogin", historyLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HistoryModules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHistoryModules(HistoryModules historyModules)
        {
            base.AddObject("HistoryModules", historyModules);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemMessage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemMessage(SystemMessage systemMessage)
        {
            base.AddObject("SystemMessage", systemMessage);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IntranetModel", Name="BinaryItens")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BinaryItens : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BinaryItens object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="binary">Initial value of the Binary property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="dataInserido">Initial value of the DataInserido property.</param>
        /// <param name="usuarioInsert">Initial value of the UsuarioInsert property.</param>
        /// <param name="dataAtualizado">Initial value of the DataAtualizado property.</param>
        /// <param name="usuarioUpdate">Initial value of the UsuarioUpdate property.</param>
        /// <param name="excluido">Initial value of the Excluido property.</param>
        public static BinaryItens CreateBinaryItens(global::System.Int32 id, global::System.Byte[] binary, global::System.String type, global::System.DateTime dataInserido, global::System.String usuarioInsert, global::System.DateTime dataAtualizado, global::System.String usuarioUpdate, global::System.Boolean excluido)
        {
            BinaryItens binaryItens = new BinaryItens();
            binaryItens.Id = id;
            binaryItens.Binary = binary;
            binaryItens.Type = type;
            binaryItens.DataInserido = dataInserido;
            binaryItens.UsuarioInsert = usuarioInsert;
            binaryItens.DataAtualizado = dataAtualizado;
            binaryItens.UsuarioUpdate = usuarioUpdate;
            binaryItens.Excluido = excluido;
            return binaryItens;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Binary
        {
            get
            {
                return StructuralObject.GetValidValue(_Binary);
            }
            set
            {
                OnBinaryChanging(value);
                ReportPropertyChanging("Binary");
                _Binary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Binary");
                OnBinaryChanged();
            }
        }
        private global::System.Byte[] _Binary;
        partial void OnBinaryChanging(global::System.Byte[] value);
        partial void OnBinaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInserido
        {
            get
            {
                return _DataInserido;
            }
            set
            {
                OnDataInseridoChanging(value);
                ReportPropertyChanging("DataInserido");
                _DataInserido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInserido");
                OnDataInseridoChanged();
            }
        }
        private global::System.DateTime _DataInserido;
        partial void OnDataInseridoChanging(global::System.DateTime value);
        partial void OnDataInseridoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioInsert
        {
            get
            {
                return _UsuarioInsert;
            }
            set
            {
                OnUsuarioInsertChanging(value);
                ReportPropertyChanging("UsuarioInsert");
                _UsuarioInsert = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioInsert");
                OnUsuarioInsertChanged();
            }
        }
        private global::System.String _UsuarioInsert;
        partial void OnUsuarioInsertChanging(global::System.String value);
        partial void OnUsuarioInsertChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAtualizado
        {
            get
            {
                return _DataAtualizado;
            }
            set
            {
                OnDataAtualizadoChanging(value);
                ReportPropertyChanging("DataAtualizado");
                _DataAtualizado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAtualizado");
                OnDataAtualizadoChanged();
            }
        }
        private global::System.DateTime _DataAtualizado;
        partial void OnDataAtualizadoChanging(global::System.DateTime value);
        partial void OnDataAtualizadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioUpdate
        {
            get
            {
                return _UsuarioUpdate;
            }
            set
            {
                OnUsuarioUpdateChanging(value);
                ReportPropertyChanging("UsuarioUpdate");
                _UsuarioUpdate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioUpdate");
                OnUsuarioUpdateChanged();
            }
        }
        private global::System.String _UsuarioUpdate;
        partial void OnUsuarioUpdateChanging(global::System.String value);
        partial void OnUsuarioUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UsuarioDelete
        {
            get
            {
                return _UsuarioDelete;
            }
            set
            {
                OnUsuarioDeleteChanging(value);
                ReportPropertyChanging("UsuarioDelete");
                _UsuarioDelete = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UsuarioDelete");
                OnUsuarioDeleteChanged();
            }
        }
        private global::System.String _UsuarioDelete;
        partial void OnUsuarioDeleteChanging(global::System.String value);
        partial void OnUsuarioDeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Excluido
        {
            get
            {
                return _Excluido;
            }
            set
            {
                OnExcluidoChanging(value);
                ReportPropertyChanging("Excluido");
                _Excluido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Excluido");
                OnExcluidoChanged();
            }
        }
        private global::System.Boolean _Excluido;
        partial void OnExcluidoChanging(global::System.Boolean value);
        partial void OnExcluidoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IntranetModel", Name="HistoryLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HistoryLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HistoryLogin object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="accessDate">Initial value of the AccessDate property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="userAgent">Initial value of the UserAgent property.</param>
        /// <param name="ip">Initial value of the Ip property.</param>
        public static HistoryLogin CreateHistoryLogin(global::System.Int32 id, global::System.DateTime accessDate, global::System.String userName, global::System.String userAgent, global::System.String ip)
        {
            HistoryLogin historyLogin = new HistoryLogin();
            historyLogin.Id = id;
            historyLogin.AccessDate = accessDate;
            historyLogin.UserName = userName;
            historyLogin.UserAgent = userAgent;
            historyLogin.Ip = ip;
            return historyLogin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AccessDate
        {
            get
            {
                return _AccessDate;
            }
            set
            {
                OnAccessDateChanging(value);
                ReportPropertyChanging("AccessDate");
                _AccessDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccessDate");
                OnAccessDateChanged();
            }
        }
        private global::System.DateTime _AccessDate;
        partial void OnAccessDateChanging(global::System.DateTime value);
        partial void OnAccessDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserAgent
        {
            get
            {
                return _UserAgent;
            }
            set
            {
                OnUserAgentChanging(value);
                ReportPropertyChanging("UserAgent");
                _UserAgent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserAgent");
                OnUserAgentChanged();
            }
        }
        private global::System.String _UserAgent;
        partial void OnUserAgentChanging(global::System.String value);
        partial void OnUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ip
        {
            get
            {
                return _Ip;
            }
            set
            {
                OnIpChanging(value);
                ReportPropertyChanging("Ip");
                _Ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ip");
                OnIpChanged();
            }
        }
        private global::System.String _Ip;
        partial void OnIpChanging(global::System.String value);
        partial void OnIpChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IntranetModel", Name="HistoryModules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HistoryModules : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HistoryModules object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static HistoryModules CreateHistoryModules(global::System.Int32 id, global::System.String userName, global::System.DateTime date, global::System.String url)
        {
            HistoryModules historyModules = new HistoryModules();
            historyModules.Id = id;
            historyModules.UserName = userName;
            historyModules.Date = date;
            historyModules.Url = url;
            return historyModules;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IntranetModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Menu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="href">Initial value of the Href property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="menuOrder">Initial value of the MenuOrder property.</param>
        /// <param name="controllerName">Initial value of the ControllerName property.</param>
        public static Menu CreateMenu(global::System.Int32 id, global::System.String href, global::System.String name, global::System.Boolean active, global::System.Int32 menuOrder, global::System.String controllerName)
        {
            Menu menu = new Menu();
            menu.Id = id;
            menu.Href = href;
            menu.Name = name;
            menu.Active = active;
            menu.MenuOrder = menuOrder;
            menu.ControllerName = controllerName;
            return menu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Href
        {
            get
            {
                return _Href;
            }
            set
            {
                OnHrefChanging(value);
                ReportPropertyChanging("Href");
                _Href = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Href");
                OnHrefChanged();
            }
        }
        private global::System.String _Href;
        partial void OnHrefChanging(global::System.String value);
        partial void OnHrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuOrder
        {
            get
            {
                return _MenuOrder;
            }
            set
            {
                OnMenuOrderChanging(value);
                ReportPropertyChanging("MenuOrder");
                _MenuOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuOrder");
                OnMenuOrderChanged();
            }
        }
        private global::System.Int32 _MenuOrder;
        partial void OnMenuOrderChanging(global::System.Int32 value);
        partial void OnMenuOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ControllerName
        {
            get
            {
                return _ControllerName;
            }
            set
            {
                OnControllerNameChanging(value);
                ReportPropertyChanging("ControllerName");
                _ControllerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ControllerName");
                OnControllerNameChanged();
            }
        }
        private global::System.String _ControllerName;
        partial void OnControllerNameChanging(global::System.String value);
        partial void OnControllerNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IntranetModel", "FK_Menu_Menu", "Menu1")]
        public EntityCollection<Menu> Menu1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("IntranetModel.FK_Menu_Menu", "Menu1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("IntranetModel.FK_Menu_Menu", "Menu1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IntranetModel", "FK_Menu_Menu", "Menu")]
        public Menu Menu2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("IntranetModel.FK_Menu_Menu", "Menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("IntranetModel.FK_Menu_Menu", "Menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Menu> Menu2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Menu>("IntranetModel.FK_Menu_Menu", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Menu>("IntranetModel.FK_Menu_Menu", "Menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IntranetModel", Name="SystemMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemMessage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="dateMessage">Initial value of the DateMessage property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static SystemMessage CreateSystemMessage(global::System.Int32 id, global::System.String message, global::System.DateTime dateMessage, global::System.Boolean active)
        {
            SystemMessage systemMessage = new SystemMessage();
            systemMessage.Id = id;
            systemMessage.Message = message;
            systemMessage.DateMessage = dateMessage;
            systemMessage.Active = active;
            return systemMessage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMessage
        {
            get
            {
                return _DateMessage;
            }
            set
            {
                OnDateMessageChanging(value);
                ReportPropertyChanging("DateMessage");
                _DateMessage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMessage");
                OnDateMessageChanged();
            }
        }
        private global::System.DateTime _DateMessage;
        partial void OnDateMessageChanging(global::System.DateTime value);
        partial void OnDateMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
    }

    #endregion

    
}
